//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.25 at 09:37:34 AM CET 
//


package eu.profinit.opendata.transform.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.profinit.opendata.transform.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.profinit.opendata.transform.jaxb
     * 
     */
    public ObjectFactory() {
        // this method is intentionally empty
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link MappedSheet }
     * 
     */
    public MappedSheet createMappedSheet() {
        return new MappedSheet();
    }

    /**
     * Create an instance of {@link PropertySet }
     * 
     */
    public PropertySet createPropertySet() {
        return new PropertySet();
    }

    /**
     * Create an instance of {@link OldRecordRetriever }
     * 
     */
    public OldRecordRetriever createOldRecordRetriever() {
        return new OldRecordRetriever();
    }

    /**
     * Create an instance of {@link PropertySetRef }
     * 
     */
    public PropertySetRef createPropertySetRef() {
        return new PropertySetRef();
    }

    /**
     * Create an instance of {@link RowFilter }
     * 
     */
    public RowFilter createRowFilter() {
        return new RowFilter();
    }

    /**
     * Create an instance of {@link RecordProperty }
     * 
     */
    public RecordProperty createRecordProperty() {
        return new RecordProperty();
    }

    /**
     * Create an instance of {@link SourceColumn }
     * 
     */
    public SourceColumn createSourceColumn() {
        return new SourceColumn();
    }

}
