//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.24 at 09:44:50 PM CET 
//


package eu.profinit.opendata.transform.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sheet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sheet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headerRow" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="filter" type="{}rowFilter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="retriever" type="{}oldRecordRetriever" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="property" type="{}recordProperty" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="propertySet" type="{}propertySetRef"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sheet", propOrder = {
    "headerRow",
    "filter",
    "retriever",
    "propertyOrPropertySet"
})
public class Sheet {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger headerRow;
    protected List<RowFilter> filter;
    protected OldRecordRetriever retriever;
    @XmlElements({
        @XmlElement(name = "property", type = RecordProperty.class),
        @XmlElement(name = "propertySet", type = PropertySetRef.class)
    })
    protected List<Object> propertyOrPropertySet;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "number")
    protected BigInteger number;

    /**
     * Gets the value of the headerRow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeaderRow() {
        return headerRow;
    }

    /**
     * Sets the value of the headerRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeaderRow(BigInteger value) {
        this.headerRow = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RowFilter }
     * 
     * 
     */
    public List<RowFilter> getFilter() {
        if (filter == null) {
            filter = new ArrayList<RowFilter>();
        }
        return this.filter;
    }

    /**
     * Gets the value of the retriever property.
     * 
     * @return
     *     possible object is
     *     {@link OldRecordRetriever }
     *     
     */
    public OldRecordRetriever getRetriever() {
        return retriever;
    }

    /**
     * Sets the value of the retriever property.
     * 
     * @param value
     *     allowed object is
     *     {@link OldRecordRetriever }
     *     
     */
    public void setRetriever(OldRecordRetriever value) {
        this.retriever = value;
    }

    /**
     * Gets the value of the propertyOrPropertySet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyOrPropertySet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyOrPropertySet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecordProperty }
     * {@link PropertySetRef }
     * 
     * 
     */
    public List<Object> getPropertyOrPropertySet() {
        if (propertyOrPropertySet == null) {
            propertyOrPropertySet = new ArrayList<Object>();
        }
        return this.propertyOrPropertySet;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

}
