/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 11-Feb-2016 3:59:00 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "partner_list_entry_partner_list_entry_id_seq"
;

/* Drop Tables */

DROP TABLE IF EXISTS "partner_list_entry" CASCADE
;

/* Create Tables */

CREATE TABLE "partner_list_entry"
(
	"authority_id" integer NOT NULL,
	"partner_id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"partner_list_entry_id" integer NOT NULL DEFAULT nextval(('"partner_list_entry_partner_list_entry_id_seq"'::text)::regclass)
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE "partner_list_entry_partner_list_entry_id_seq" INCREMENT 1 START 1
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "partner_list_entry" ADD CONSTRAINT "PK_PartnerListEntry"
	PRIMARY KEY ("partner_list_entry_id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "partner_list_entry" ADD CONSTRAINT "FK_partner_list_entry_entity"
	FOREIGN KEY ("authority_id") REFERENCES "entity" ("entity_id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "partner_list_entry" ADD CONSTRAINT "FK_partner_list_entry_entity_02"
	FOREIGN KEY ("partner_id") REFERENCES "entity" ("entity_id") ON DELETE No Action ON UPDATE No Action
;
