/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 13-Feb-2016 2:20:55 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "unresolved_relationship_unresolved_relationship_id_seq"
;

/* Drop Tables */

DROP TABLE IF EXISTS "unresolved_relationship" CASCADE
;

/* Create Tables */

CREATE TABLE "unresolved_relationship"
(
	"bound_authority_identifier" varchar(50)	 NOT NULL,
	"saved_record_id" integer NOT NULL,
	"unresolved_relationship_id" integer NOT NULL DEFAULT nextval(('"unresolved_relationship_unresolved_relationship_id_seq"'::text)::regclass)
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE "unresolved_relationship_unresolved_relationship_id_seq" INCREMENT 1 START 1
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "unresolved_relationship" ADD CONSTRAINT "PK_unresolved_relationship"
	PRIMARY KEY ("unresolved_relationship_id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "unresolved_relationship" ADD CONSTRAINT "FK_unresolved_relationship_record"
	FOREIGN KEY ("saved_record_id") REFERENCES "record" ("record_id") ON DELETE No Action ON UPDATE No Action
;
