/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 07-XI-2015 12:29:21 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "retrieval_retrievalid_seq"
;

DROP SEQUENCE IF EXISTS "record_recordid_seq"
;

DROP SEQUENCE IF EXISTS "entity_entityid_seq"
;

DROP SEQUENCE IF EXISTS "datasource_datasourceid_seq"
;

DROP SEQUENCE IF EXISTS "datainstance_datainstanceid_seq"
;

DROP SEQUENCE IF EXISTS "datainstance_datasourceid_seq"
;

/* Drop Tables */

DROP TABLE IF EXISTS "Retrieval" CASCADE
;

DROP TABLE IF EXISTS "RecordType" CASCADE
;

DROP TABLE IF EXISTS "Record" CASCADE
;

DROP TABLE IF EXISTS "Periodicity" CASCADE
;

DROP TABLE IF EXISTS "EntityType" CASCADE
;

DROP TABLE IF EXISTS "Entity" CASCADE
;

DROP TABLE IF EXISTS "DataSource" CASCADE
;

DROP TABLE IF EXISTS "DataInstance" CASCADE
;

DROP TABLE IF EXISTS "AuthorityRole" CASCADE
;

/* Create Tables */

CREATE TABLE "Retrieval"
(
	"date" timestamp without time zone NOT NULL,
	"failureReason" varchar(1000)	 NULL,
	"numBadRecords" int NOT NULL,
	"numRecordsInserted" int NOT NULL,
	"success" boolean NOT NULL,
	"retrievalID" integer NOT NULL DEFAULT nextval(('"retrieval_retrievalid_seq"'::text)::regclass),
	"dataInstanceID" integer NULL
)
;

CREATE TABLE "RecordType"
(
	"recordType" varchar(50)	 NOT NULL
)
;

CREATE TABLE "Record"
(
	"amountCZKWithVAT" double precision NULL,
	"amountCZKWithoutVAT" double precision NULL,
	"authorityIdentifier" varchar(50)	 NULL,
	"currency" varchar(3)	 NOT NULL,
	"dateCreated" date NOT NULL,
	"dateOfExpiry" date NULL,
	"dateOfPayment" date NULL,
	"dueDate" date NULL,
	"inEffect" boolean NULL,
	"masterID" varchar(50)	 NOT NULL,
	"originalCurrencyAmount" double precision NULL,
	"partnerCode" varchar(50)	 NULL,
	"subject" varchar(255)	 NULL,
	"variableSymbol" varchar(50)	 NULL,
	"recordID" integer NOT NULL DEFAULT nextval(('"record_recordid_seq"'::text)::regclass),
	"partner" integer NULL,
	"authority" integer NOT NULL,
	"parentID" integer NULL,
	"retrievalID" integer NULL,
	"recordType" varchar(50)	 NOT NULL,
	"authorityRole" varchar(50)	 NULL
)
;

CREATE TABLE "Periodicity"
(
	"periodicity" varchar(50)	 NOT NULL
)
;

CREATE TABLE "EntityType"
(
	"entityType" varchar(50)	 NOT NULL
)
;

CREATE TABLE "Entity"
(
	"DIC" varchar(50)	 NULL,
	"ICO" varchar(50)	 NULL,
	"isPublic" boolean NOT NULL,
	"name" varchar(255)	 NOT NULL,
	"entityID" integer NOT NULL DEFAULT nextval(('"entity_entityid_seq"'::text)::regclass),
	"entityType" varchar(50)	 NOT NULL
)
;

CREATE TABLE "DataSource"
(
	"isIncremental" boolean NOT NULL,
	"lastProcessedDate" timestamp without time zone NULL,
	"dataSourceID" integer NOT NULL DEFAULT nextval(('"datasource_datasourceid_seq"'::text)::regclass),
	"entityID" integer NOT NULL,
	"recordType" varchar(50)	 NOT NULL,
	"periodicity" varchar(50)	 NOT NULL
)
;

CREATE TABLE "DataInstance"
(
	"format" varchar(3)	 NOT NULL,
	"processed" boolean NOT NULL,
	"URL" varchar(255)	 NOT NULL,
	"dataInstanceID" integer NOT NULL DEFAULT nextval(('"datainstance_datainstanceid_seq"'::text)::regclass),
	"dataSourceID" integer NOT NULL DEFAULT nextval(('"datainstance_datasourceid_seq"'::text)::regclass)
)
;

CREATE TABLE "AuthorityRole"
(
	"authorityRole" varchar(50)	 NOT NULL
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE "retrieval_retrievalid_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "record_recordid_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "entity_entityid_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "datasource_datasourceid_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "datainstance_datainstanceid_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "datainstance_datasourceid_seq" INCREMENT 1 START 1
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Retrieval" ADD CONSTRAINT "PK_Retrieval"
	PRIMARY KEY ("retrievalID")
;

ALTER TABLE "RecordType" ADD CONSTRAINT "PK_RecordType"
	PRIMARY KEY ("recordType")
;

ALTER TABLE "Record" ADD CONSTRAINT "PK_Record"
	PRIMARY KEY ("recordID")
;

ALTER TABLE "Periodicity" ADD CONSTRAINT "PK_Periodicity"
	PRIMARY KEY ("periodicity")
;

ALTER TABLE "EntityType" ADD CONSTRAINT "PK_EntityType"
	PRIMARY KEY ("entityType")
;

ALTER TABLE "Entity" ADD CONSTRAINT "PK_Entity"
	PRIMARY KEY ("entityID")
;

ALTER TABLE "DataSource" ADD CONSTRAINT "PK_DataSource"
	PRIMARY KEY ("dataSourceID")
;

ALTER TABLE "DataInstance" ADD CONSTRAINT "PK_DataInstance"
	PRIMARY KEY ("dataInstanceID")
;

ALTER TABLE "AuthorityRole" ADD CONSTRAINT "PK_AuthorityRole"
	PRIMARY KEY ("authorityRole")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Retrieval" ADD CONSTRAINT "FK_Retrieval_DataInstance"
	FOREIGN KEY ("dataInstanceID") REFERENCES "DataInstance" ("dataInstanceID") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "Record" ADD CONSTRAINT "FK_Record_AuthorityRole"
	FOREIGN KEY ("authorityRole") REFERENCES "AuthorityRole" ("authorityRole") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Record" ADD CONSTRAINT "FK_Record_RecordType"
	FOREIGN KEY ("recordType") REFERENCES "RecordType" ("recordType") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Record" ADD CONSTRAINT "FK_partner"
	FOREIGN KEY ("partner") REFERENCES "Entity" ("entityID") ON DELETE Set Null ON UPDATE Set Null
;

ALTER TABLE "Record" ADD CONSTRAINT "FK_authority"
	FOREIGN KEY ("authority") REFERENCES "Entity" ("entityID") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "Record" ADD CONSTRAINT "FK_Record_Record"
	FOREIGN KEY ("parentID") REFERENCES "Record" ("recordID") ON DELETE Set Null ON UPDATE No Action
;

ALTER TABLE "Record" ADD CONSTRAINT "FK_Record_Retrieval"
	FOREIGN KEY ("retrievalID") REFERENCES "Retrieval" ("retrievalID") ON DELETE Set Null ON UPDATE Set Null
;

ALTER TABLE "Entity" ADD CONSTRAINT "FK_Entity_EntityType"
	FOREIGN KEY ("entityType") REFERENCES "EntityType" ("entityType") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "DataSource" ADD CONSTRAINT "FK_DataSource_Periodicity"
	FOREIGN KEY ("periodicity") REFERENCES "Periodicity" ("periodicity") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "DataSource" ADD CONSTRAINT "FK_DataSource_RecordType"
	FOREIGN KEY ("recordType") REFERENCES "RecordType" ("recordType") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "DataSource" ADD CONSTRAINT "FK_DataSource_Entity"
	FOREIGN KEY ("entityID") REFERENCES "Entity" ("entityID") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "DataInstance" ADD CONSTRAINT "FK_DataInstance_DataSource"
	FOREIGN KEY ("dataSourceID") REFERENCES "DataSource" ("dataSourceID") ON DELETE Cascade ON UPDATE Cascade
;
